env:
  browser: false
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 2017
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - 0
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
