export interface ApiKey {

    /**
     * A string that uniquely identifies this API key.
     */
    id: string;

    /**
     * The application ID that this object belongs to.
     */
    applicationId: string;

    /**
     * A human-readable description.
     */
    description: string;

    /**
     * The scopes granted to the API key.
     */
    scopes: string[];

    /**
     * Meta information object. Contrary to the rest of the BadgeUp API, adding custom fields to the API Key meta object is not permistted.
     */
    meta: {
        created: Date
    };

    /**
     * Unique API key generated by BadgeUp.
     */
    token: string;
}

export interface ApiKeyScope {
    scope: string;
    description: string;
}
